services:
  - type: web
    name: backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: node backend/index.js
    plan: free
    regions:
      - frankfurt

  - type: web
    name: frontend
    env: static
    buildCommand: ""
    staticPublishPath: frontend
    plan: free
    regions:
      - frankfurt
