services:
  - type: web
    name: backend
    env: node
    buildCommand: npm install
    startCommand: node backend/index.js
    plan: free
    regions:
      - frankfurt

  - type: web
    name: frontend
    env: static
    buildCommand: ""
    startCommand: ""
    plan: free
    regions:
      - frankfurt
    publish: /frontend
